spring:
  application:
    name: mgr-applications
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
      accept-single-value-as-array: true
  datasource:
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_DATABASE:okapi_modules}
  liquibase:
    change-log: classpath:changelog/changelog-master.xml
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}
    security:
      protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
    ssl:
      key-store-password: ${KAFKA_SSL_KEYSTORE_PASSWORD:}
      key-store-location: ${KAFKA_SSL_KEYSTORE_LOCATION:}
      trust-store-password: ${KAFKA_SSL_TRUSTSTORE_PASSWORD:}
      trust-store-location: ${KAFKA_SSL_TRUSTSTORE_LOCATION:}
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        retries: 5
        spring.json.add.type.headers: false
  cloud:
    openfeign:
      okhttp:
        enabled: true

application:
  router:
    path-prefix: ${ROUTER_PATH_PREFIX:}
  http-client:
    read-timeout: 30000
    connection-timeout: 300000
  far-mode:
    enabled: ${FAR_MODE:false}
  security:
    enabled: ${SECURITY_ENABLED:false}
  kong:
    enabled: ${KONG_INTEGRATION_ENABLED:true}
    url: ${KONG_ADMIN_URL:${kong.url:}}
    module-self-url: ${MODULE_URL:http://mgr-applications:8081}
    register-module: ${REGISTER_MODULE_IN_KONG:true}
    connect-timeout: ${KONG_CONNECT_TIMEOUT:}
    read-timeout: ${KONG_READ_TIMEOUT:}
    write-timeout: ${KONG_WRITE_TIMEOUT:}
    retries: ${KONG_RETRIES:}
    tls:
      enabled: ${KONG_TLS_ENABLED:false}
      trust-store-path: ${KONG_TLS_TRUSTSTORE_PATH:}
      trust-store-password: ${KONG_TLS_TRUSTSTORE_PASSWORD:}
      trust-store-type: ${KONG_TLS_TRUSTSTORE_TYPE:}
  okapi:
    enabled: ${OKAPI_INTEGRATION_ENABLED:true}
    url: ${OKAPI_URL:${okapi.url:}}
    mod-authtoken-url: ${MOD_AUTHTOKEN_URL}
  environment: ${ENV:folio}
  kafka:
    topics:
      - name: discovery
        numPartitions: ${KAFKA_DISCOVERY_TOPIC_PARTITIONS:1}
        replicationFactor: ${KAFKA_DISCOVERY_TOPIC_REPLICATION_FACTOR:}
  keycloak:
    enabled: ${KC_INTEGRATION_ENABLED:false}
    url: ${KC_URL:http://keycloak:8080}
    admin:
      client_id: ${KC_ADMIN_CLIENT_ID:folio-backend-admin-client}
      username: ${KC_ADMIN_USERNAME:}
      password: ${KC_ADMIN_PASSWORD:}
      grant_type: ${KC_ADMIN_GRANT_TYPE:client_credentials}
    import:
      enabled: ${KC_IMPORT_ENABLED:false}
    client:
      client_id: ${KC_CLIENT_ID:mgr-applications}
    tls:
      enabled: ${KC_CLIENT_TLS_ENABLED:false}
      trust-store-path: ${KC_CLIENT_TLS_TRUSTSTORE_PATH}
      trust-store-password: ${KC_CLIENT_TLS_TRUSTSTORE_PASSWORD}
      trust-store-type: ${KC_CLIENT_TLS_TRUSTSTORE_TYPE}
    jwt-cache-configuration:
      validate-uri: ${KC_AUTH_TOKEN_VALIDATE_URI:false}
      jwks-refresh-interval: ${KC_JWKS_REFRESH_INTERVAL:60}
      forced-jwks-refresh-interval: ${KC_FORCED_JWKS_REFRESH_INTERVAL:60}
  secret-store:
    type: ${SECRET_STORE_TYPE:}
    aws-ssm:
      region: ${SECRET_STORE_AWS_SSM_REGION:}
      use-iam: ${SECRET_STORE_AWS_SSM_USE_IAM:true}
      ecs-credentials-endpoint: ${SECRET_STORE_AWS_SSM_ECS_CREDENTIALS_ENDPOINT:}
      ecs-credentials-path: ${SECRET_STORE_AWS_SSM_ECS_CREDENTIALS_PATH:}
    vault:
      token: ${SECRET_STORE_VAULT_TOKEN:}
      address: ${SECRET_STORE_VAULT_ADDRESS:}
      enable-ssl: ${SECRET_STORE_VAULT_ENABLE_SSL:false}
      pem-file-path: ${SECRET_STORE_VAULT_PEM_FILE_PATH:}
      keystore-password: ${SECRET_STORE_VAULT_KEYSTORE_PASSWORD:}
      keystore-file-path: ${SECRET_STORE_VAULT_KEYSTORE_FILE_PATH:}
      truststore-file-path: ${SECRET_STORE_VAULT_TRUSTSTORE_FILE_PATH:}
  validation:
    default-mode: ${VALIDATION_MODE:basic}

tenant:
  entitlement:
    url: ${TE_URL:${te.url:http://mgr-tenant-entitlements:8081}}
    tls:
      enabled: ${TE_TLS_ENABLED:false}
      trust-store-path: ${TE_TLS_TRUSTSTORE_PATH:}
      trust-store-password: ${TE_TLS_TRUSTSTORE_PASSWORD:}
      trust-store-type: ${TE_TLS_TRUSTSTORE_TYPE:}

folio:
  jpa:
    repository:
      base-packages: org.folio.am.*

server:
  port: ${SERVER_PORT:8081}
  max-http-request-header-size: ${MAX_HTTP_REQUEST_HEADER_SIZE:200KB}
  compression:
    enabled: true
    mime-types: text/html,text/plain,text/css,application/javascript,application/json
  ssl:
    enabled: ${SERVER_SSL_ENABLED:false}
    key-store: ${SERVER_SSL_KEY_STORE}
    key-store-type: ${SERVER_SSL_KEY_STORE_TYPE:BCFKS}
    key-store-provider: ${SERVER_SSL_KEY_STORE_PROVIDER:BCFIPS}
    key-store-password: ${SERVER_SSL_KEY_STORE_PASSWORD}
    key-password: ${SERVER_SSL_KEY_PASSWORD}

management:
  endpoints.web:
    base-path: /admin
    exposure:
      include: info,health,liquibase,threaddump,heapdump,httptrace,loggers

feign:
  client:
    config:
      okapi:
        connectTimeout: 30000
        readTimeout: 300000

messaging:
  trx-outbox:
    enabled: true
    publishing:
      task-execution:
        pool:
          keep-alive: 600s
      scheduling:
        enabled: true

routemanagement:
  enable: ${ROUTEMANAGEMENT_ENABLE:false}
