hibernate.types.print.banner=false
hypersistence.utils.jackson.object.mapper=org.folio.am.config.HibernateCustomObjectMapper
hypersistence.utils.json.serializer=org.folio.am.config.HibernateCustomJsonSerializer
